version: '3.7'

services:

  app:
    build: artifacts
    ports:
      - "8080:8080"
    environment:
      - SPRING_CREDIT_GATE_URL=http://nodejs:9999/payment
      - SPRING_PAYMENT_GATE_URL=http://nodejs:9999/payment
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/app
      - SPRING_DATASOURCE_USERNAME=app
      - SPRING_DATASOURCE_PASSWORD=pass
    depends_on:
      - mysql
      - nodejs

  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
    volumes:
      - ./data:/var/lib/mysql

  nodejs:
    image: node:latest
    ports:
      - '9999:9999'
    working_dir: /opt/app
    volumes:
      - ./gate-simulator:/opt/app
    command: npm start

#  http://localhost:3000/credit
