version: '3.7'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-docker
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
    volumes:
      - ./data:/var/lib/mysql


  postgres:
    image: postgres:13-alpine
    container_name: postgres-docker
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app
    volumes:
      - ./data:/var/lib/postgresql

  nodejs:
    image: node:latest
    container_name: node-docker
    ports:
      - '3000:3000'
    working_dir: /opt/app
    volumes:
      - ./gate-simulator:/opt/app
    command: npm start

#  http://localhost:3000/credit
